### ISSUE TITLE
from szurubooru.func import scores, cannot import name 'scores'

### ISSUE THREAD

**Issue by cam-peterson** [rr-/szurubooru#106]
Hello!

I was trying to get this booru running, but I have found this problem:

```
$ ./host-waitress
Traceback (most recent call last):
  File "./host-waitress", line 13, in <module>
    from szurubooru.facade import create_app
  File "/home/cam/szuru/server/szurubooru/facade.py", line 9, in <module>
    from szurubooru import api, middleware
  File "/home/cam/szuru/server/szurubooru/api/__init__.py", line 1, in <module>
    import szurubooru.api.info_api
  File "/home/cam/szuru/server/szurubooru/api/info_api.py", line 5, in <module>
    from szurubooru.func import posts, users, util
  File "/home/cam/szuru/server/szurubooru/func/posts.py", line 4, in <module>
    from szurubooru.func import (
  File "/home/cam/szuru/server/szurubooru/func/scores.py", line 3, in <module>
    from szurubooru.func import favorites
  File "/home/cam/szuru/server/szurubooru/func/favorites.py", line 3, in <module>
    from szurubooru.func import scores
ImportError: cannot import name 'scores'
```

I was wondering if you know what caused it? Thank you

My python --version says Python 3.4.2

**Comment by rr-** [comment]
No idea, works fine on my end. Is there any chance the server is missing some files?

**Comment by cam-peterson** [comment]
I don't think there any missing files, i tried  deleting the repo and making a fresh clone to make sure but I still have the same problem. Here is some of the output from ./test:  https://gist.github.com/cam-peterson/a57055678ba9231b813a725e9f84e4dd

**Comment by rr-** [comment]
I think it might be that Python 3.5 is more forgiving about circular dependencies, and there is one such dependency between scores and favorites. I'll try to refactor the code so that it doesn't have such dependency.

**Comment by rr-** [comment]
I opted for the easy way out and pushed the `import` statements inside the functions that needed them. Please let me know if this solves the issue for you.

**Comment by cam-peterson** [comment]
Thank you very much this seems to fix it!
