### ISSUE TITLE
Feature request: Search in notes and other text

### ISSUE THREAD

**Issue by Darksonn** [rr-/szurubooru#118]
A lot of the images in my szurubooru contain text. I would like to have the ability to search in the text. Text recognition for the images would also be nice, but it could be added manually with notes.

**Comment by rr-** [comment]
Text recognition is too complex and won't be happening
I'll implement search in text notes soon

**Comment by rr-** [comment]
Done in 0b21d98c9bb26db6b5e9aa40e8877af33ec7a390

**Comment by Darksonn** [comment]
After pulling I cannot start the server.
```
szuru@boats:~/szuru/server$ alembic upgrade head
Traceback (most recent call last):
  File "/home/szuru/.python/bin/alembic", line 9, in <module>
    load_entry_point('alembic==0.8.10', 'console_scripts', 'alembic')()
  File "/home/szuru/.python/lib/python3.5/site-packages/alembic/config.py", line 479, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/szuru/.python/lib/python3.5/site-packages/alembic/config.py", line 473, in main
    self.run_cmd(cfg, options)
  File "/home/szuru/.python/lib/python3.5/site-packages/alembic/config.py", line 456, in run_cmd
    **dict((k, getattr(options, k)) for k in kwarg)
  File "/home/szuru/.python/lib/python3.5/site-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/home/szuru/.python/lib/python3.5/site-packages/alembic/script/base.py", line 416, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/szuru/.python/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/szuru/.python/lib/python3.5/site-packages/alembic/util/compat.py", line 68, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "szurubooru/migrations/env.py", line 12, in <module>
    import szurubooru.db.base
ImportError: No module named 'szurubooru.db.base'; 'szurubooru.db' is not a package
```
    szuru@boats:szuru/server$ waitress-serve --port 6666 szurubooru.facade:app
    Error: Bad module 'szurubooru.facade'
    There was an exception (ImportError) importing your module.
    
    It had these arguments: 
    1. cannot import name 'Type'

**Comment by Darksonn** [comment]
I don't know if it matters, but there appear to be several files untracked by git:

```
szuru@boats:~/szuru$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        server/szurubooru/__pycache__/
        server/szurubooru/api/__pycache__/
        server/szurubooru/db/
        server/szurubooru/func/__pycache__/
        server/szurubooru/middleware/__pycache__/
        server/szurubooru/migrations/__pycache__/
        server/szurubooru/migrations/versions/__pycache__/
        server/szurubooru/rest/__pycache__/
        server/szurubooru/search/__pycache__/
        server/szurubooru/search/configs/__pycache__/
        server/szurubooru/tests/__pycache__/
        server/szurubooru/tests/api/__pycache__/
        server/szurubooru/tests/db/
        server/szurubooru/tests/func/__pycache__/
        server/szurubooru/tests/rest/__pycache__/
        server/szurubooru/tests/search/__pycache__/
        server/szurubooru/tests/search/configs/__pycache__/

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by rr-** [comment]
Meh, I expected this to happen when I was pushing ad842ee8a54c57463b8e28b52970f173ea1d64ea...

On Python 3.6.0:

```
(python_modules) rr-@tornado:~/src/maintained/szurubooru/server$ waitress-serve --port 6666 szurubooru.facade:app
Serving on http://0.0.0.0:6666
```

although the `typing` module is available from 3.5.0.

`server/szurubooru/tests/db/` probably contains only `__pycache__`; all `__pycache__` can be safely removed.

**Comment by Darksonn** [comment]
I'll build 3.6.0 then

**Comment by rr-** [comment]
That would be hip - I could ditch ugly `# type: str` in favor of PEP 526's variable annotations
Sorry for the inconvenience :(

**Comment by rr-** [comment]
Tested on `python3.5` and indeed added two small fixes, but none of them had to do with the above error:

```
1. cannot import name 'Type'
````

```console
(python_modules) rr-@tornado:~/src/maintained/szurubooru/server$ waitress-serve --port 6666 szurubooru.facade:app
Serving on http://0.0.0.0:6666
^C%
(python_modules) rr-@tornado:~/src/maintained/szurubooru/server$ whence waitress-serve
/home/rr-/src/maintained/szurubooru/server/python_modules/bin/waitress-serve
(python_modules) rr-@tornado:~/src/maintained/szurubooru/server$ whence python
/home/rr-/src/maintained/szurubooru/server/python_modules/bin/python
(python_modules) rr-@tornado:~/src/maintained/szurubooru/server$ python --version
Python 3.5.3
```

**Comment by Darksonn** [comment]
Using python 3.6.0 and after completely rebuilding the git repo, `alembic upgrade head` fails with this error:

````
szuru@boats:~/szuru/server$ alembic upgrade head 
Traceback (most recent call last):
  File "/home/szuru/.python3.6.0/bin/alembic", line 11, in <module>
    load_entry_point('alembic==0.8.10', 'console_scripts', 'alembic')()
  File "/home/szuru/.python3.6.0/lib/python3.6/site-packages/alembic/config.py", line 479, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/szuru/.python3.6.0/lib/python3.6/site-packages/alembic/config.py", line 473, in main
    self.run_cmd(cfg, options)
  File "/home/szuru/.python3.6.0/lib/python3.6/site-packages/alembic/config.py", line 456, in run_cmd
    **dict((k, getattr(options, k)) for k in kwarg)
  File "/home/szuru/.python3.6.0/lib/python3.6/site-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/home/szuru/.python3.6.0/lib/python3.6/site-packages/alembic/script/base.py", line 416, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/szuru/.python3.6.0/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/szuru/.python3.6.0/lib/python3.6/site-packages/alembic/util/compat.py", line 68, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "szurubooru/migrations/env.py", line 12, in <module>
    import szurubooru.db.base
ModuleNotFoundError: No module named 'szurubooru.db.base'; 'szurubooru.db' is not a package
````

**Comment by Darksonn** [comment]
Also, I had to modify the `skimage` line in the `requirements.txt` to `scikit-image`.

**Comment by rr-** [comment]
Can reproduce; fixed both

**Comment by Darksonn** [comment]
It works.

**Comment by rr-** [comment]
Thanks for the bug reports :+1:
