### ISSUE TITLE
Installation process: 'npm run build' throws 'sh: 1: node: not found'

### ISSUE THREAD

**Issue by MaxValue** [rr-/szurubooru#176]
When running `npm run build` from the [installation process in order to compile the frontend](https://github.com/rr-/szurubooru/blob/master/INSTALL.md#preparing-szurubooru-for-first-run), it gives the following error trace without building successfully:

```
> node build.js

sh: 1: node: not found

npm ERR! Linux 4.13.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! szurubooru@ build: `node build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the szurubooru@ build script 'node build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the szurubooru package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs szurubooru
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls szurubooru
npm ERR! There is likely additional logging output above.
```

This is the `npm-debug.log` file it wanted me to include here:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle szurubooru@~prebuild: szurubooru@
6 silly lifecycle szurubooru@~prebuild: no script for prebuild, continuing
7 info lifecycle szurubooru@~build: szurubooru@
8 verbose lifecycle szurubooru@~build: unsafe-perm in lifecycle true
9 verbose lifecycle szurubooru@~build: PATH: /usr/share/npm/bin/node-gyp-bin:/home/USERNAME/Path-To-Git-Clone/client/node_modules/.bin:/home/USERNAME/Path-To-Git-Clone/server/python_modules/bin:/home/USERNAME/bin:/home/USERNAME/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/USERNAME/bin
10 verbose lifecycle szurubooru@~build: CWD: /home/USERNAME/Path-To-Git-Clone/client
11 silly lifecycle szurubooru@~build: Args: [ '-c', 'node build.js' ]
12 info lifecycle szurubooru@~build: Failed to exec build script
13 verbose stack Error: szurubooru@ build: `node build.js`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid szurubooru@
15 verbose cwd /home/USERNAME/Path-To-Git-Clone/client
16 error Linux 4.13.0-45-generic
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
18 error node v4.2.6
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error szurubooru@ build: `node build.js`
24 error spawn ENOENT
25 error Failed at the szurubooru@ build script 'node build.js'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the szurubooru package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     node build.js
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs szurubooru
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls szurubooru
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

Again, please forgive me for opening another issue :bowing_man:

**Comment by ev1l0rd** [comment]
You somehow have npm installed and not node. Try installing node again.

**Comment by MaxValue** [comment]
Is this a dependency? In the [installation process](https://github.com/rr-/szurubooru/blob/master/INSTALL.md#installing-hard-dependencies) it is not written to install node, only npm (out of all JavaScript-related packages).

So, how do I install it? Sorry for asking this, I am not a big JavaScript guy.

**Comment by mserajnik** [comment]
@MaxValue Depending on which OS you're on, there are several ways to install Node.

If you go to the [official website](https://nodejs.org/en/) you'll find installers (those will install Node and npm). Or you can install via a package manager for your OS (e.g., [Homebrew](https://brew.sh/) if you're on macOS or [Apt](https://wiki.debian.org/Apt) if you're on a Debian-based Linux).

**Comment by rr-** [comment]
Whoa, I didn't know you could install `npm` without `node`.

**Comment by MaxValue** [comment]
Hmm. Regarding what ev1l0rd said:

Okay, then I guess they won’t add this as dependency to the apt package. Maybe I should have read what optional additional packages were available... I will try that and tell you guys if I got node working.

**Comment by sgsunder** [comment]
It seems unlikely that you have npm installed but somehow managed to not have node installed. More likely is that npm is somehow not finding node on your `PATH`

Does running `which node` in a shell give any results? You can also try running `node build.js` directly, instead of `npm run build`, to see if that works.
