### ISSUE TITLE
Error when uploading videos with sound

### ISSUE THREAD

**Issue by CorePoint** [rr-/szurubooru#207]
When i try to upload videos with sound i get this error:
edit:
correction it doesn't happen with all files with sound, i'm going to provide an example.
https://ptpb.pw/wYYy
```
Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/waitress/channel.py", line 338, in service
     task.service()
   File "/usr/local/lib/python3.6/site-packages/waitress/task.py", line 169, in service
     self.execute()
   File "/usr/local/lib/python3.6/site-packages/waitress/task.py", line 399, in execute
     app_iter = self.channel.server.application(env, start_response)
   File "/opt/app/szurubooru/rest/app.py", line 99, in application
     response = handler(ctx, match.groupdict())
   File "/opt/app/szurubooru/api/post_api.py", line 68, in create_post
     posts.test_sound(post, content)
   File "/opt/app/szurubooru/func/posts.py", line 481, in test_sound
     if images.Image(content).check_for_sound():
   File "/opt/app/szurubooru/func/images.py", line 161, in check_for_sound
     ], get_logs=True).decode('utf-8')
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 3702: invalid continuation byte
```
Thank you for this great piece of software!

**Comment by CorePoint** [comment]
Thanks man!
I'll try that, if you want me to i can do the PR.

**Comment by sgsunder** [comment]
Hmm, you could try my fork of this repo. It already my fix implemented plus a bunch of other minor fixes and code cleanups (although I don't know what else would have fixed it). I use this version almost every day for uploads and I haven't run across this issue yet

You can just copy the [`docker-compose.yml`](https://gist.githubusercontent.com/sgsunder/b694d50dbb10e9db355f193d2794ee3d/raw/61af945f7b72eb321e8b05840a7e321e238d238a/docker-compose.yml) and [`.env`](https://raw.githubusercontent.com/sgsunder/szurubooru/master/example.env) files into a directory  to try it out. These use the images I built and uploaded on Docker Hub (`sgsunder/szurubooru-client` and `sgsunder/szurubooru-api`) so they should be completely identical to what I'm running right now.

**Comment by rr-** [comment]
Why not backport your changes to upstream?
