### ISSUE TITLE
Can't upload gif through api

### ISSUE THREAD

**Issue by lee-brown** [rr-/szurubooru#221]
I'm trying to upload GIFs from the internet to the booru. Images work fine, but if I try uploading a GIF I get an internal server error. 

I found that if I include tags while uploading the GIF via the API it results in an error. Uploading a GIF without tags through the API works fine. 

Portion of Server log after uploading gif with tags:

```
api_1            | [2019-02-05 13:51:16] szurubooru.middleware.request_logger POST /posts/ (user=Catlee, queries=8)
api_1            | [2019-02-05 13:51:16] waitress Exception when serving /posts/
api_1            | Traceback (most recent call last):
api_1            |   File "/usr/local/lib/python3.6/site-packages/waitress/channel.py", line 336, in service
api_1            |     task.service()
api_1            |   File "/usr/local/lib/python3.6/site-packages/waitress/task.py", line 175, in service
api_1            |     self.execute()
api_1            |   File "/usr/local/lib/python3.6/site-packages/waitress/task.py", line 452, in execute
api_1            |     app_iter = self.channel.server.application(env, start_response)
api_1            |   File "/opt/app/szurubooru/rest/app.py", line 99, in application
api_1            |     response = handler(ctx, match.groupdict())
api_1            |   File "/opt/app/szurubooru/api/post_api.py", line 74, in create_post
api_1            |     alternate_format_posts = posts.generate_alternate_formats(post, content)
api_1            |   File "/opt/app/szurubooru/func/posts.py", line 444, in generate_alternate_formats
api_1            |     for tag_name in [tag.names for tag in post.tags]]
api_1            |   File "/opt/app/szurubooru/func/posts.py", line 444, in <listcomp>
api_1            |     for tag_name in [tag.names for tag in post.tags]]
api_1            | AttributeError: 'InstrumentedList' object has no attribute 'name'
```

**Comment by sgsunder** [comment]
I can't test this at the moment but the bug seems to be here:

https://github.com/rr-/szurubooru/blob/2fdd8cb3ab4f45796a4e9dd858caaaf215d19ef3/server/szurubooru/func/posts.py#L442-L444

and I think this should be replaced with:

```python
tag_names = [tag.first_name for tag in post.tags]
```
