### ISSUE TITLE
FATAL:  password authentication failed for user "szuru"

### ISSUE THREAD

**Issue by AkgunFatih** [rr-/szurubooru#264]
i get this error after running the last step "docker-compose up -d"
```sql
Looking for ElasticSearch connection...


Connected to ElasticSearch!


Traceback (most recent call last):


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2262, in _wrap_pool_connect


    return fn()


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection


    return _ConnectionFairy._checkout(self)


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout


    fairy = _ConnectionRecord.checkout(pool)


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout


    rec = pool._do_get()


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get


    return self._create_connection()


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection


    return _ConnectionRecord(self)


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__


    self.__connect(first_connect_check=True)


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect


    connection = pool._invoke_creator(self)


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect


    return dialect.connect(*cargs, **cparams)


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect


    return self.dbapi.connect(*cargs, **cparams)


  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect


    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)


psycopg2.OperationalError: FATAL:  password authentication failed for user "szuru"






The above exception was the direct cause of the following exception:




Traceback (most recent call last):


  File "/usr/local/bin/alembic", line 10, in <module>


    sys.exit(main())


  File "/usr/local/lib/python3.6/site-packages/alembic/config.py", line 540, in main


    CommandLine(prog=prog).main(argv=argv)


  File "/usr/local/lib/python3.6/site-packages/alembic/config.py", line 534, in main


    self.run_cmd(cfg, options)


  File "/usr/local/lib/python3.6/site-packages/alembic/config.py", line 514, in run_cmd


    **dict((k, getattr(options, k, None)) for k in kwarg)


  File "/usr/local/lib/python3.6/site-packages/alembic/command.py", line 276, in upgrade


    script.run_env()


  File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 475, in run_env


    util.load_python_file(self.dir, "env.py")


  File "/usr/local/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 90, in load_python_file


    module = load_module_py(module_id, path)


  File "/usr/local/lib/python3.6/site-packages/alembic/util/compat.py", line 156, in load_module_py


    spec.loader.exec_module(module)


  File "<frozen importlib._bootstrap_external>", line 678, in exec_module


  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed


  File "szurubooru/migrations/env.py", line 72, in <module>


    run_migrations_online()


  File "szurubooru/migrations/env.py", line 59, in run_migrations_online


    with connectable.connect() as connection:


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2193, in connect


    return self._connection_cls(self, **kwargs)


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 103, in __init__


    else engine.raw_connection()


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2293, in raw_connection


    self.pool.unique_connection, _connection


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2266, in _wrap_pool_connect


    e, dialect, self


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1536, in _handle_dbapi_exception_noconnection


    util.raise_from_cause(sqlalchemy_exception, exc_info)


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause


    reraise(type(exception), exception, tb=exc_tb, cause=cause)


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise


    raise value.with_traceback(tb)


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2262, in _wrap_pool_connect


    return fn()


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection


    return _ConnectionFairy._checkout(self)


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout


    fairy = _ConnectionRecord.checkout(pool)


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout


    rec = pool._do_get()


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get


    return self._create_connection()


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection


    return _ConnectionRecord(self)


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__


    self.__connect(first_connect_check=True)


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect


    connection = pool._invoke_creator(self)


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect


    return dialect.connect(*cargs, **cparams)


  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect


    return self.dbapi.connect(*cargs, **cparams)


  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect


    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)


sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "szuru"




(Background on this error at: http://sqlalche.me/e/e3q8)


```

**Comment by sgsunder** [comment]
It seems like you didn't pass the right database password through the environment variables.

- Did you copy `example.env` to `.env` and remember to set a value for `POSTGRES_PASSWORD`?
- Are you using the database in the docker-compose script as provided, or using some different database.
- Did you have one value for `POSTGRES_PASSWORD` when you first started up the database container, then changed it later on?

**Comment by AkgunFatih** [comment]
this is my env file

```env
# Database credentials
POSTGRES_USER=szuru
POSTGRES_PASSWORD=szuru

# This shows up on the homescreen, indicating build information
BUILD_INFO=latest

# Port to expose HTTP service
# Set to 127.0.0.1:8080 if you wish to reverse-proxy the docker's port,
# otherwise the port specified here will be publicly accessible
PORT=6969

# Directory to store image data
MOUNT_DATA=/var/local/szurubooru/data

# Directory to store database files
MOUNT_SQL=/var/local/szurubooru/sql
```

and this is my docker-compose file

```yaml
## Example Docker Compose configuration
##
## Use this as a template to set up docker-compose, or as guide to set up other
## orchestration services
version: '2'

services:
  api:
    build:
      context: ./server
    depends_on:
      - sql
      - elasticsearch
    environment:
      ## These should be the names of the dependent containers listed above,
      ## or FQDNs/IP addresses if these services are running outside of Docker
      POSTGRES_HOST: sql
      ESEARCH_HOST: elasticsearch
      ## Credentials for database:
      POSTGRES_USER:szuru
      POSTGRES_PASSWORD:szuru
      ## Commented Values are Default:
      #POSTGRES_DB: defaults to same as POSTGRES_USER
      #POSTGRES_PORT: 5432
      #ESEARCH_PORT: 9200
      #ESEARCH_INDEX: szurubooru
      #LOG_SQL: 0 (1 for verbose SQL logs)
    volumes:
      - "${MOUNT_DATA}:/data"
      - "./server/config.yaml:/opt/app/config.yaml"
  client:
    build:
      context: ./client
      args:
        BUILD_INFO:
    depends_on:
      - api
    environment:
      BACKEND_HOST: api
    volumes:
      - "${MOUNT_DATA}:/data:ro"
    ports:
      - "${PORT}:80"
  sql:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER:szuru
      POSTGRES_PASSWORD:szuru
    volumes:
      - "${MOUNT_SQL}:/var/lib/postgresql/data"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.1
    environment:
      ## Specifies the Java heap size used
      ## Read
      ##  https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
      ## for more info
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - index:/usr/share/elasticsearch/data

volumes:
  index: # Scratch space for ElasticSearch index, will be rebuilt if lost
```

i dont see anything wrong in it do you ?

**Comment by AkgunFatih** [comment]
when using root user everything works great
