### ISSUE TITLE
wait_for_status error when starting server

### ISSUE THREAD

**Issue by noirscape** [rr-/szurubooru#285]
Error occurs on this line. Seems to be caused by elasticsearch taking a while to start, therefore hitting the timeout limit for szurubooru. 

Restarting the server container fixes the issue (presumably since elasticsearch is already started by then.)

https://github.com/rr-/szurubooru/blob/master/server/szurubooru/facade.py#L134

**Comment by noirscape** [comment]
Complete docker logs of `server`:

```

server_1         | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
server_1         | INFO  [alembic.runtime.migration] Will assume transactional DDL.
server_1         | Starting szurubooru API on port 6666
server_1         | Traceback (most recent call last):
server_1         |   File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
server_1         |     (self._dns_host, self.port), self.timeout, **extra_kw
server_1         |   File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
server_1         |     raise err
server_1         |   File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
server_1         |     sock.connect(sa)
server_1         | ConnectionRefusedError: [Errno 111] Connection refused
server_1         |
server_1         | During handling of the above exception, another exception occurred:
server_1         |
server_1         | Traceback (most recent call last):
server_1         |   File "/usr/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 217, in perform_request
server_1         |     method, url, body, retries=Retry(False), headers=request_headers, **kw
server_1         |   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
server_1         |     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
server_1         |   File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 376, in increment
server_1         |     raise six.reraise(type(error), error, _stacktrace)
server_1         |   File "/usr/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
server_1         |     raise value
server_1         |   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
server_1         |     chunked=chunked,
server_1         |   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
server_1         |     conn.request(method, url, **httplib_request_kw)
server_1         |   File "/usr/lib/python3.7/http/client.py", line 1244, in request
server_1         |     self._send_request(method, url, body, headers, encode_chunked)
server_1         |   File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
server_1         |     self.endheaders(body, encode_chunked=encode_chunked)
server_1         |   File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
server_1         |     self._send_output(message_body, encode_chunked=encode_chunked)
server_1         |   File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
server_1         |     self.send(msg)
server_1         |   File "/usr/lib/python3.7/http/client.py", line 966, in send
server_1         |     self.connect()
server_1         |   File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 184, in connect
server_1         |     conn = self._new_conn()
server_1         |   File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
server_1         |     self, "Failed to establish a new connection: %s" % e
server_1         | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f48ef7bba50>: Failed to establish a new connection: [Errno 111] Connection refused
server_1         |
server_1         | During handling of the above exception, another exception occurred:
server_1         |
server_1         | Traceback (most recent call last):
server_1         |   File "/usr/bin/waitress-serve-3", line 11, in <module>
server_1         |     load_entry_point('waitress==1.1.0', 'console_scripts', 'waitress-serve')()
server_1         |   File "/usr/lib/python3.7/site-packages/waitress/runner.py", line 259, in run
server_1         |     app = resolve(module, obj_name)
server_1         |   File "/usr/lib/python3.7/site-packages/waitress/runner.py", line 201, in resolve
server_1         |     obj = __import__(module_name, fromlist=segments[:1])
server_1         |   File "/opt/app/szurubooru/facade.py", line 152, in <module>
server_1         |     app = create_app()  # pylint: disable=invalid-name
server_1         |   File "/opt/app/szurubooru/facade.py", line 134, in create_app
server_1         |     wait_for_status='yellow', request_timeout=30)
server_1         |   File "/usr/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
server_1         |     return func(*args, params=params, **kwargs)
server_1         |   File "/usr/lib/python3.7/site-packages/elasticsearch/client/cluster.py", line 43, in health
server_1         |     "GET", _make_path("_cluster", "health", index), params=params
server_1         |   File "/usr/lib/python3.7/site-packages/elasticsearch/transport.py", line 353, in perform_request
server_1         |     timeout=timeout,
server_1         |   File "/usr/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 229, in perform_request
server_1         |     raise ConnectionError("N/A", str(e), e)
server_1         | elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f48ef7bba50>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f48ef7bba50>: Failed to establish a new connection: [Errno 111] Connection refused)```

**Comment by sgsunder** [comment]
Related to the conversation in #284 

Bumped the timeout to 2 minutes. Let me know if this isn't enough.

**Comment by noirscape** [comment]
Would love to test this, but can't pull image since the build failed.

**Comment by sgsunder** [comment]
@rr- Can you look at the build logs and let me know why the latest commit 4f5ea9c fails to build? Both the server and client build and test fine on my laptop. It's also a fairly trivial commit so I don't expect any from it. I'm guessing there's some error internal to Docker Hub.

**Comment by sgsunder** [comment]
@rr- 
It doesn't appear that I have any access to view build status on either of these

https://hub.docker.com/r/rrdash/szurubooru-server
https://hub.docker.com/r/rrdash/szurubooru-client

Not really sure how to add me as a collaborator, though.

In the meantime, you can probably manually trigger both image builds and hopefully the HTTP 503 error has passed.

**Comment by rr-** [comment]
@sgsunder should be good now. Thanks.
As for the matter of sharing the administrative access to the builds - I think we should have created an organization, rather than linking it to my private account. I tried to do so, but it says that the org name `szurubooru` is already taken :confused: Apparently, the only way to resolve this issue is to contact a DockerHub employee directly, as seen in their Q&A portal. For now, it's too much of a hassle IMO. Let's see how the builds fare for the few next months and if it does become a problem, as opposed to being a single incident, I'll deal with it.
