### ISSUE TITLE
Bug: Safety query in GET API calls returns 500 response

### ISSUE THREAD

**Issue by Tkompuras** [rr-/szurubooru#376]
#### I'm new to this and may be doing something stupid but if I sent GET requests:

`http://localhost:8080/api/posts/?query=safety%3Aquestionable` 
or 
`http://localhost:8080/api/posts/?query=safety%3Aunsafe` 
they return 200 fine.

However 
`http://localhost:8080/api/posts/?query=safety%3Asafe` 
and 
`http://localhost:8080/api/posts/?query=safety%3Asketchy` 
return 500 Internal Server Error. 

Is this a bug or am I doing something wrong? Can anyone recreate it?

**Comment by neobooru** [comment]
I can't seem to recreate it. This doesn't have to mean that it's not a bug, but on my end it seems to work fine.

**Comment by Tkompuras** [comment]
Would you like any specific info? I did a pretty default installation I think. I'm running docker on Win10 with WSL.

**Comment by Tkompuras** [comment]
Welp, cool. I run it again after I previously tried without changing anything and now both work. Weird stuff

**Comment by Tkompuras** [comment]
```
[2021-02-26 13:29:29] waitress Exception while serving /posts/
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/waitress/channel.py", line 349, in service
task.service()
File "/usr/lib/python3.8/site-packages/waitress/task.py", line 169, in service
self.execute()
File "/usr/lib/python3.8/site-packages/waitress/task.py", line 439, in execute
app_iter = self.channel.server.application(environ, start_response)
File "/opt/app/szurubooru/rest/app.py", line 104, in application
response = handler(ctx, match.groupdict())
File "/opt/app/szurubooru/api/post_api.py", line 48, in get_posts
return _search_executor.execute_and_serialize(
File "/opt/app/szurubooru/search/executor.py", line 131, in execute_and_serialize
"results": list([serializer(entity) for entity in entities]),
File "/opt/app/szurubooru/search/executor.py", line 131, in <listcomp>
"results": list([serializer(entity) for entity in entities]),
File "/opt/app/szurubooru/api/post_api.py", line 49, in <lambda>
ctx, lambda post: _serialize_post(ctx, post)
File "/opt/app/szurubooru/api/post_api.py", line 37, in _serialize_post
return posts.serialize_post(
File "/opt/app/szurubooru/func/posts.py", line 353, in serialize_post
return PostSerializer(post, auth_user).serialize(options)
File "/opt/app/szurubooru/func/serialization.py", line 25, in serialize
ret[key] = factory()
File "/opt/app/szurubooru/func/posts.py", line 268, in serialize_relations
for rel in self.post.relations
File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 287, in __get__
return self.impl.get(instance_state(instance), dict_)
File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 723, in get
value = self.callable_(state, passive)
File "/usr/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 707, in _load_for_state
raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <Post at 0x7f8c2696afd0> is not bound to a Session; lazy load operation of attribute 'relations' cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)
```
I think these were the server logs at the time. Don't know if they can be of use.

**Comment by Tkompuras** [comment]
Ok title is wrong since it happens to many different requests. It is usually fixed if I restart the containers.

**Comment by CrawlerBleak** [comment]
I had the same issue. In my case, restarting didn't help, but there were three tags without names in the database. I added back their names manually in `psql`, and the issue went away.
