### ISSUE TITLE
How can I replace the site icons?

### ISSUE THREAD

**Issue by nottaw** [rr-/szurubooru#469]
I've replaced the files in `client/img` with the icons I want, `docker-compose down` and `docker-compose up -d` the containers, and cleared my browser cache, but I still see the default favicon. Is there something else I need to do?

**Comment by skybldev** [comment]
Have you made sure to tell Docker to build the client from local files? Here is an example from my fork: https://github.com/skybldev/szurubooru/blob/master/docker-compose.yml#L29

**Comment by nottaw** [comment]
> Have you made sure to tell Docker to build the client from local files? Here is an example from my fork: https://github.com/skybldev/szurubooru/blob/master/docker-compose.yml#L29
> 
> After that, you can run `docker-compose up` and it will build from local files.

Thanks for the quick response. I hadn't done that, so I've replaced the `image` lines to match your example, but the build failed.

```
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.arg
v[0] = '"'"'/tmp/pip-install-d0_7afv3/pyheif_f130e8b63a3f498c9d43d52a4c2411c7/setup.py'"'"'; __file__='"'"'/tmp/
pip-install-d0_7afv3/pyheif_f130e8b63a3f498c9d43d52a4c2411c7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', o
pen)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'e
xec'"'"'))' install --record /tmp/pip-record-lsu70upj/install-record.txt --single-version-externally-managed --c
ompile --install-headers /usr/include/python3.8/pyheif Check the logs for full command output.
```

The logs show this:

```
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
PermissionError: [Errno 13] Permission denied
```

This looks similar to [this issue](https://github.com/rr-/szurubooru/issues/216). Do I have to `chown` anything like with that?

**Comment by skybldev** [comment]
Yes. Most likely, your user does not have permission to use the Docker daemon. There is a quick but dangerous solution: `sudo setfacl --modify user:<youruser>:rw /var/run/docker/sock`. That should only be done for testing/development; don't do this on a production machine.

**Comment by nottaw** [comment]
Since I _am_ doing this on a production machine, is the long-term solution safe for that? If so I'll give it a try.

**Comment by skybldev** [comment]
It should be, as long as you also keep your user secure, since granting it permissions to the Docker daemon in the first place can be a bit risky. If you would like to be extra safe, you could try this: https://docs.docker.com/engine/security/rootless/

**Comment by nottaw** [comment]
I still got the same error after adding my user to the `docker` group and logging back in, although this time rather than the Python stack trace I got this `logs` output:

```
nottaw@debian:~/szuru$ docker-compose logs
Attaching to 
```

**Comment by skybldev** [comment]
What is the output of `docker-compose up` before you ran `logs`? If it has the same error, it should have spat it out during the build stage. Please try running `docker build client --no-cache` or send the output of `docker-compose up`.

**Comment by nottaw** [comment]
Running `docker build client --no-cache` gives me this:

```
Sending build context to Docker daemon  1.458MB
Step 1/23 : FROM --platform=$BUILDPLATFORM node:lts as builder
failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument
```

Here's the output of `docker-compose up`:

```
Building server
Sending build context to Docker daemon  1.005MB
Step 1/31 : ARG ALPINE_VERSION=3.13
Step 2/31 : FROM alpine:$ALPINE_VERSION as prereqs
 ---> 6b7b3256dabe
Step 3/31 : WORKDIR /opt/app
 ---> Using cache
 ---> 3d9e71f97cc4
Step 4/31 : RUN apk --no-cache add         python3         python3-dev         ffmpeg         py3-pip         py3-yaml         py3-psycopg2         py3-sqlalchemy         py3-certifi         py3-numpy         py3-pillow         py3-pynacl         py3-tz         py3-pyrfc3339         build-base  && apk --no-cache add         libheif         libavif         libheif-dev         libavif-dev  && pip3 install --no-cache-dir --disable-pip-version-check         alembic         "coloredlogs==5.0"         heif-image-plugin         youtube_dl         pillow-avif-plugin  && apk --no-cache del py3-pip
 ---> Running in 968b54a83fcd
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/134) Installing libgcc (10.2.1_pre1-r3)
(2/134) Installing libstdc++ (10.2.1_pre1-r3)
(3/134) Installing binutils (2.35.2-r1)
(4/134) Installing libmagic (5.39-r0)
(5/134) Installing file (5.39-r0)
(6/134) Installing libgomp (10.2.1_pre1-r3)
(7/134) Installing libatomic (10.2.1_pre1-r3)
(8/134) Installing libgphobos (10.2.1_pre1-r3)
(9/134) Installing gmp (6.2.1-r1)
(10/134) Installing isl22 (0.22-r0)
(11/134) Installing mpfr4 (4.1.0-r0)
(12/134) Installing mpc1 (1.2.0-r0)
(13/134) Installing gcc (10.2.1_pre1-r3)
(14/134) Installing musl-dev (1.2.2-r1)
(15/134) Installing libc-dev (0.7.2-r3)
(16/134) Installing g++ (10.2.1_pre1-r3)
(17/134) Installing make (4.3-r0)
(18/134) Installing fortify-headers (1.1-r0)
(19/134) Installing patch (2.7.6-r7)
(20/134) Installing build-base (0.5-r2)
(21/134) Installing sdl2 (2.0.14-r0)
(22/134) Installing libxau (1.0.9-r0)
(23/134) Installing libbsd (0.10.0-r0)
(24/134) Installing libxdmcp (1.1.3-r0)
(25/134) Installing libxcb (1.14-r1)
(26/134) Installing libx11 (1.7.1-r0)
(27/134) Installing aom-libs (1.0.0-r1)
(28/134) Installing alsa-lib (1.2.4-r2)
(29/134) Installing expat (2.2.10-r6)
(30/134) Installing brotli-libs (1.0.9-r3)
(31/134) Installing libbz2 (1.0.8-r1)
(32/134) Installing libpng (1.6.37-r1)
(33/134) Installing freetype (2.10.4-r1)
(34/134) Installing libuuid (2.37.4-r0)
(35/134) Installing fontconfig (2.13.1-r3)
(36/134) Installing fribidi (1.0.10-r0)
(37/134) Installing libffi (3.3-r2)
(38/134) Installing libintl (0.20.2-r2)
(39/134) Installing libblkid (2.37.4-r0)
(40/134) Installing libmount (2.37.4-r0)
(41/134) Installing pcre (8.44-r0)
(42/134) Installing glib (2.66.8-r0)
(43/134) Installing graphite2 (1.3.14-r0)
(44/134) Installing harfbuzz (2.7.4-r1)
(45/134) Installing libass (0.15.0-r0)
(46/134) Installing libdav1d (0.8.1-r0)
(47/134) Installing nettle (3.7.3-r0)
(48/134) Installing p11-kit (0.23.22-r0)
(49/134) Installing libtasn1 (4.16.0-r1)
(50/134) Installing libunistring (0.9.10-r0)
(51/134) Installing gnutls (3.7.1-r0)
(52/134) Installing ncurses-terminfo-base (6.2_p20210109-r0)
(53/134) Installing ncurses-libs (6.2_p20210109-r0)
(54/134) Installing lame (3.100-r0)
(55/134) Installing opus (1.3.1-r1)
(56/134) Installing soxr (0.1.3-r2)
(57/134) Installing libsrt (1.4.2-r0)
(58/134) Installing libssh (0.9.5-r0)
(59/134) Installing libogg (1.3.4-r0)
(60/134) Installing libtheora (1.1.1-r16)
(61/134) Installing libjpeg-turbo (2.1.0-r0)
(62/134) Installing v4l-utils-libs (1.20.0-r0)
(63/134) Installing libxext (1.3.4-r0)
(64/134) Installing libxfixes (5.0.3-r2)
(65/134) Installing libpciaccess (0.16-r0)
(66/134) Installing libdrm (2.4.104-r0)
(67/134) Installing wayland-libs-client (1.18.0-r5)
(68/134) Installing libva (2.10.0-r0)
(69/134) Installing libvdpau (1.4-r0)
(70/134) Installing vidstab (1.1.0-r1)
(71/134) Installing libvorbis (1.3.7-r0)
(72/134) Installing libvpx (1.9.0-r0)
(73/134) Installing vulkan-loader (1.2.137-r0)
(74/134) Installing x264-libs (20191119-r1)
(75/134) Installing x265-libs (3.4-r0)
(76/134) Installing xvidcore (1.3.7-r1)
(77/134) Installing ffmpeg-libs (4.3.3-r0)
(78/134) Installing ffmpeg (4.3.3-r0)
(79/134) Installing gdbm (1.19-r0)
(80/134) Installing xz-libs (5.2.5-r0)
(81/134) Installing readline (8.1.0-r0)
(82/134) Installing sqlite-libs (3.34.1-r0)
(83/134) Installing python3 (3.8.10-r0)
(84/134) Installing py3-certifi (2020.6.20-r0)
(85/134) Installing libquadmath (10.2.1_pre1-r3)
(86/134) Installing libgfortran (10.2.1_pre1-r3)
(87/134) Installing openblas (0.3.13-r0)
(88/134) Installing py3-numpy (1.19.5-r0)
(89/134) Installing py3-olefile (0.46-r4)
(90/134) Installing libimagequant (2.13.1-r0)
(91/134) Installing lcms2 (2.11-r0)
(92/134) Installing openjpeg (2.4.0-r1)
(93/134) Installing tiff (4.2.0-r0)
(94/134) Installing libwebp (1.1.0-r0)
(95/134) Installing py3-pillow (7.2.0-r2)
(96/134) Installing py3-appdirs (1.4.4-r1)
(97/134) Installing py3-ordered-set (4.0.2-r0)
(98/134) Installing py3-parsing (2.4.7-r1)
(99/134) Installing py3-six (1.15.0-r0)
(100/134) Installing py3-packaging (20.9-r0)
(101/134) Installing py3-setuptools (51.3.3-r0)
(102/134) Installing py3-chardet (4.0.0-r0)
(103/134) Installing py3-idna (3.1-r0)
(104/134) Installing py3-urllib3 (1.26.2-r1)
(105/134) Installing py3-requests (2.25.1-r1)
(106/134) Installing py3-msgpack (1.0.2-r0)
(107/134) Installing py3-lockfile (0.12.2-r3)
(108/134) Installing py3-cachecontrol (0.12.6-r0)
(109/134) Installing py3-colorama (0.4.4-r0)
(110/134) Installing py3-contextlib2 (0.6.0-r0)
(111/134) Installing py3-distlib (0.3.1-r1)
(112/134) Installing py3-distro (1.5.0-r1)
(113/134) Installing py3-webencodings (0.5.1-r3)
(114/134) Installing py3-html5lib (1.1-r0)
(115/134) Installing py3-pytoml (0.1.21-r0)
(116/134) Installing py3-pep517 (0.9.1-r0)
(117/134) Installing py3-progress (1.5-r0)
(118/134) Installing py3-retrying (1.3.3-r0)
(119/134) Installing py3-toml (0.10.2-r0)
(120/134) Installing py3-pip (20.3.4-r0)
(121/134) Installing libsasl (2.1.27-r10)
(122/134) Installing libldap (2.4.57-r1)
(123/134) Installing libpq (13.6-r0)
(124/134) Installing py3-psycopg2 (2.8.6-r0)
(125/134) Installing py3-cparser (2.20-r0)
(126/134) Installing py3-cffi (1.14.4-r0)
(127/134) Installing py3-pynacl (1.4.0-r0)
(128/134) Installing py3-tz (2020.5-r0)
(129/134) Installing py3-pyrfc3339 (1.1-r3)
(130/134) Installing py3-sqlalchemy (1.3.21-r0)
(131/134) Installing yaml (0.2.5-r0)
(132/134) Installing py3-yaml (5.3.1-r2)
(133/134) Installing pkgconf (1.7.3-r0)
(134/134) Installing python3-dev (3.8.10-r0)
Executing busybox-1.32.1-r7.trigger
OK: 440 MiB in 148 packages
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/8) Installing libavif (0.8.4-r0)
(2/8) Installing libavif-dev (0.8.4-r0)
(3/8) Installing libde265 (1.0.4-r0)
(4/8) Installing libheif (1.9.1-r0)
(5/8) Installing aom-dev (1.0.0-r1)
(6/8) Installing x265-dev (3.4-r0)
(7/8) Installing libde265-dev (1.0.4-r0)
(8/8) Installing libheif-dev (1.9.1-r0)
Executing busybox-1.32.1-r7.trigger
OK: 450 MiB in 156 packages
Collecting alembic
  Downloading alembic-1.7.6-py3-none-any.whl (210 kB)
Collecting coloredlogs==5.0
  Downloading coloredlogs-5.0.tar.gz (24 kB)
Collecting heif-image-plugin
  Downloading heif-image-plugin-0.3.2.tar.gz (5.3 kB)
Collecting youtube_dl
  Downloading youtube_dl-2021.12.17-py2.py3-none-any.whl (1.9 MB)
Collecting pillow-avif-plugin
  Downloading pillow-avif-plugin-1.2.1.tar.gz (11 kB)
Collecting humanfriendly>=1.42
  Downloading humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Collecting importlib-resources
  Downloading importlib_resources-5.4.0-py3-none-any.whl (28 kB)
Collecting Mako
  Downloading Mako-1.2.0-py3-none-any.whl (78 kB)
Collecting importlib-metadata
  Downloading importlib_metadata-4.11.2-py3-none-any.whl (17 kB)
Requirement already satisfied: SQLAlchemy>=1.3.0 in /usr/lib/python3.8/site-packages (from alembic) (1.3.21)
Collecting pyheif>=0.6.1
  Downloading pyheif-0.7.0.tar.gz (22 kB)
Collecting piexif>=1.1.3
  Downloading piexif-1.1.3-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: cffi>=1.0.0 in /usr/lib/python3.8/site-packages (from pyheif>=0.6.1->heif-image-plugin) (1.14.4)
Requirement already satisfied: pycparser in /usr/lib/python3.8/site-packages (from cffi>=1.0.0->pyheif>=0.6.1->heif-image-plugin) (2.20)
Collecting zipp>=0.5
  Downloading zipp-3.7.0-py3-none-any.whl (5.3 kB)
Collecting MarkupSafe>=0.9.2
  Downloading MarkupSafe-2.1.0.tar.gz (18 kB)
Using legacy 'setup.py install' for coloredlogs, since package 'wheel' is not installed.
Using legacy 'setup.py install' for heif-image-plugin, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pyheif, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pillow-avif-plugin, since package 'wheel' is not installed.
Using legacy 'setup.py install' for MarkupSafe, since package 'wheel' is not installed.
Installing collected packages: zipp, MarkupSafe, pyheif, piexif, Mako, importlib-resources, importlib-metadata, humanfriendly, youtube-dl, pillow-avif-plugin, heif-image-plugin, coloredlogs, alembic
    Running setup.py install for MarkupSafe: started
    Running setup.py install for MarkupSafe: finished with status 'done'
    Running setup.py install for pyheif: started
    Running setup.py install for pyheif: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xalj1ary/pyheif_4802cfbba9b049979608a82097865b9e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xalj1ary/pyheif_4802cfbba9b049979608a82097865b9e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-duftz9e7/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/pyheif
         cwd: /tmp/pip-install-xalj1ary/pyheif_4802cfbba9b049979608a82097865b9e/
    Complete output (125 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/pyheif
    copying pyheif/reader.py -> build/lib.linux-x86_64-3.8/pyheif
    copying pyheif/constants.py -> build/lib.linux-x86_64-3.8/pyheif
    copying pyheif/__init__.py -> build/lib.linux-x86_64-3.8/pyheif
    copying pyheif/writer.py -> build/lib.linux-x86_64-3.8/pyheif
    copying pyheif/error.py -> build/lib.linux-x86_64-3.8/pyheif
    creating build/lib.linux-x86_64-3.8/pyheif/data
    copying pyheif/data/version.txt -> build/lib.linux-x86_64-3.8/pyheif/data
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-3.8/_libheif_cffi.c'
    creating build/temp.linux-x86_64-3.8
    building '_libheif_cffi' extension
    creating build/temp.linux-x86_64-3.8/build
    creating build/temp.linux-x86_64-3.8/build/temp.linux-x86_64-3.8
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include -I/usr/include -I/opt/local/include -I/usr/include/python3.8 -c build/temp.linux-x86_64-3.8/_libheif_cffi.c -o build/temp.linux-x86_64-3.8/build/temp.linux-x86_64-3.8/_libheif_cffi.o
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_const_heif_error_Color_profile_does_not_exist':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:1362:12: error: 'heif_error_Color_profile_does_not_exist' undeclared (first use in this function); did you mean '_cffi_const_heif_error_Color_profile_does_not_exist'?
     1362 |   int n = (heif_error_Color_profile_does_not_exist) <= 0;
          |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          |            _cffi_const_heif_error_Color_profile_does_not_exist
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:1362:12: note: each undeclared identifier is reported only once for each function it appears in
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_const_heif_suberror_Wrong_tile_image_pixel_depth':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:1761:12: error: 'heif_suberror_Wrong_tile_image_pixel_depth' undeclared (first use in this function); did you mean '_cffi_const_heif_suberror_Wrong_tile_image_pixel_depth'?
     1761 |   int n = (heif_suberror_Wrong_tile_image_pixel_depth) <= 0;
          |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          |            _cffi_const_heif_suberror_Wrong_tile_image_pixel_depth
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_d_heif_brand_to_fourcc':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:1992:3: warning: implicit declaration of function 'heif_brand_to_fourcc'; did you mean '_cffi_d_heif_brand_to_fourcc'? [-Wimplicit-function-declaration]
     1992 |   heif_brand_to_fourcc(x0, x1);
          |   ^~~~~~~~~~~~~~~~~~~~
          |   _cffi_d_heif_brand_to_fourcc
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_d_heif_fourcc_to_brand':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:3025:10: warning: implicit declaration of function 'heif_fourcc_to_brand'; did you mean '_cffi_d_heif_fourcc_to_brand'? [-Wimplicit-function-declaration]
     3025 |   return heif_fourcc_to_brand(x0);
          |          ^~~~~~~~~~~~~~~~~~~~
          |          _cffi_d_heif_fourcc_to_brand
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_d_heif_free_list_of_compatible_brands':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:3063:3: warning: implicit declaration of function 'heif_free_list_of_compatible_brands'; did you mean '_cffi_d_heif_free_list_of_compatible_brands'? [-Wimplicit-function-declaration]
     3063 |   heif_free_list_of_compatible_brands(x0);
          |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          |   _cffi_d_heif_free_list_of_compatible_brands
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_d_heif_has_compatible_brand':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:3277:10: warning: implicit declaration of function 'heif_has_compatible_brand'; did you mean '_cffi_d_heif_has_compatible_brand'? [-Wimplicit-function-declaration]
     3277 |   return heif_has_compatible_brand(x0, x1, x2);
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~
          |          _cffi_d_heif_has_compatible_brand
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_d_heif_image_handle_free_auxiliary_types':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:4049:3: warning: implicit declaration of function 'heif_image_handle_free_auxiliary_types'; did you mean '_cffi_d_heif_image_handle_free_auxiliary_types'? [-Wimplicit-function-declaration]
     4049 |   heif_image_handle_free_auxiliary_types(x0, x1);
          |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          |   _cffi_d_heif_image_handle_free_auxiliary_types
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_d_heif_image_handle_get_auxiliary_image_handle':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:4100:10: warning: implicit declaration of function 'heif_image_handle_get_auxiliary_image_handle'; did you mean '_cffi_d_heif_image_handle_get_auxiliary_image_handle'? [-Wimplicit-function-declaration]
     4100 |   return heif_image_handle_get_auxiliary_image_handle(x0, x1, x2);
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          |          _cffi_d_heif_image_handle_get_auxiliary_image_handle
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:4100:10: error: incompatible types when returning type 'int' but 'struct heif_error' was expected
     4100 |   return heif_image_handle_get_auxiliary_image_handle(x0, x1, x2);
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_f_heif_image_handle_get_auxiliary_image_handle':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:4144:14: error: incompatible types when assigning to type 'struct heif_error' from type 'int'
     4144 |   { result = heif_image_handle_get_auxiliary_image_handle(x0, x1, x2); }
          |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_d_heif_image_handle_get_auxiliary_type':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:4162:10: warning: implicit declaration of function 'heif_image_handle_get_auxiliary_type'; did you mean '_cffi_d_heif_image_handle_get_auxiliary_type'? [-Wimplicit-function-declaration]
     4162 |   return heif_image_handle_get_auxiliary_type(x0, x1);
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          |          _cffi_d_heif_image_handle_get_auxiliary_type
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:4162:10: error: incompatible types when returning type 'int' but 'struct heif_error' was expected
     4162 |   return heif_image_handle_get_auxiliary_type(x0, x1);
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_f_heif_image_handle_get_auxiliary_type':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:4200:14: error: incompatible types when assigning to type 'struct heif_error' from type 'int'
     4200 |   { result = heif_image_handle_get_auxiliary_type(x0, x1); }
          |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_d_heif_image_handle_get_list_of_auxiliary_image_IDs':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:4529:10: warning: implicit declaration of function 'heif_image_handle_get_list_of_auxiliary_image_IDs'; did you mean '_cffi_d_heif_image_handle_get_list_of_auxiliary_image_IDs'? [-Wimplicit-function-declaration]
     4529 |   return heif_image_handle_get_list_of_auxiliary_image_IDs(x0, x1, x2, x3);
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          |          _cffi_d_heif_image_handle_get_list_of_auxiliary_image_IDs
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_d_heif_image_handle_get_number_of_auxiliary_images':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:5082:10: warning: implicit declaration of function 'heif_image_handle_get_number_of_auxiliary_images'; did you mean '_cffi_d_heif_image_handle_get_number_of_auxiliary_images'? [-Wimplicit-function-declaration]
     5082 |   return heif_image_handle_get_number_of_auxiliary_images(x0, x1);
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          |          _cffi_d_heif_image_handle_get_number_of_auxiliary_images
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_d_heif_image_handle_is_premultiplied_alpha':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:5529:10: warning: implicit declaration of function 'heif_image_handle_is_premultiplied_alpha'; did you mean '_cffi_d_heif_image_handle_is_premultiplied_alpha'? [-Wimplicit-function-declaration]
     5529 |   return heif_image_handle_is_premultiplied_alpha(x0);
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          |          _cffi_d_heif_image_handle_is_premultiplied_alpha
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_d_heif_list_compatible_brands':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:5932:10: warning: implicit declaration of function 'heif_list_compatible_brands'; did you mean '_cffi_d_heif_list_compatible_brands'? [-Wimplicit-function-declaration]
     5932 |   return heif_list_compatible_brands(x0, x1, x2, x3);
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
          |          _cffi_d_heif_list_compatible_brands
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:5932:10: error: incompatible types when returning type 'int' but 'struct heif_error' was expected
     5932 |   return heif_list_compatible_brands(x0, x1, x2, x3);
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_f_heif_list_compatible_brands':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:5987:14: error: incompatible types when assigning to type 'struct heif_error' from type 'int'
     5987 |   { result = heif_list_compatible_brands(x0, x1, x2, x3); }
          |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_d_heif_read_main_brand':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:6115:10: warning: implicit declaration of function 'heif_read_ma
in_brand'; did you mean 'heif_main_brand'? [-Wimplicit-function-declaration]
     6115 |   return heif_read_main_brand(x0, x1);
          |          ^~~~~~~~~~~~~~~~~~~~
          |          heif_main_brand
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_d_heif_list_compatible_brands':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:5933:1: warning: control reaches end of non-void function [-Wret
urn-type]
     5933 | }
          | ^
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_d_heif_image_handle_get_auxiliary_type':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:4163:1: warning: control reaches end of non-void function [-Wret
urn-type]
     4163 | }
          | ^
    build/temp.linux-x86_64-3.8/_libheif_cffi.c: In function '_cffi_d_heif_image_handle_get_auxiliary_image_hand
le':
    build/temp.linux-x86_64-3.8/_libheif_cffi.c:4101:1: warning: control reaches end of non-void function [-Wret
urn-type]
     4101 | }
          | ^
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.arg
v[0] = '"'"'/tmp/pip-install-xalj1ary/pyheif_4802cfbba9b049979608a82097865b9e/setup.py'"'"'; __file__='"'"'/tmp/
pip-install-xalj1ary/pyheif_4802cfbba9b049979608a82097865b9e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', o
pen)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'e
xec'"'"'))' install --record /tmp/pip-record-duftz9e7/install-record.txt --single-version-externally-managed --c
ompile --install-headers /usr/include/python3.8/pyheif Check the logs for full command output.
The command '/bin/sh -c apk --no-cache add         python3         python3-dev         ffmpeg         py3-pip   
      py3-yaml         py3-psycopg2         py3-sqlalchemy         py3-certifi         py3-numpy         py3-pil
low         py3-pynacl         py3-tz         py3-pyrfc3339         build-base  && apk --no-cache add         li
bheif         libavif         libheif-dev         libavif-dev  && pip3 install --no-cache-dir --disable-pip-vers
ion-check         alembic         "coloredlogs==5.0"         heif-image-plugin         youtube_dl         pillow
-avif-plugin  && apk --no-cache del py3-pip' returned a non-zero code: 1
ERROR: Service 'server' failed to build : Build failed
```

**Comment by skybldev** [comment]
For the first, run `export DOCKER_BUILDKIT=1; export COMPOSE_DOCKER_CLI_BUILD=1` before `docker-compose build`.

As for the second, I'm not really sure what's going on. It should be pulling the image from Docker Hub, not building it. If you do have some modifications on the server and need to build it locally, then you might want to consider installing `libheif`. I'll have to get back to you on this if I figure out anything else.

**Comment by neobooru** [comment]
You don't need to build the server image if you only make changes to the client directory. I believe the server image is a bit more tricky to build as well. 

So change/revert
```yml
server:
  build: server
```
to
```yml
server:
  image: szurubooru/server:latest
```

Could you show us your docker-compose.yml if it still doesn't work when not building the server image?

**Comment by nottaw** [comment]
> You don't need to build the server image if you only make changes to the client directory. I believe the server image is a bit more tricky to build as well.
> 
> So change/revert
> 
> ```yaml
> server:
>   build: server
> ```
> 
> to
> 
> ```yaml
> server:
>   image: szurubooru/server:latest
> ```
> 
> Could you show us your docker-compose.yml if it still doesn't work when not building the server image?

That worked - I was able to build it and I can see my new icons in the running client. Still not sure why I couldn't build the server image (I didn't make any changes to it), but I only set it to build for consistency with the client so I've reverted it. Thanks for the help.
