### ISSUE TITLE
Issue while running `alembic upgrade head` when hosting without docker

### ISSUE THREAD

**Issue by ziimro** [rr-/szurubooru#479]
```
(python_modules) [zim@piarch server]$ alembic upgrade head
Traceback (most recent call last):
  File "/home/zim/szuru/server/python_modules/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/zim/szuru/server/python_modules/lib/python3.10/site-packages/alembic/config.py", line 588, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/zim/szuru/server/python_modules/lib/python3.10/site-packages/alembic/config.py", line 582, in main
    self.run_cmd(cfg, options)
  File "/home/zim/szuru/server/python_modules/lib/python3.10/site-packages/alembic/config.py", line 559, in run_cmd
    fn(
  File "/home/zim/szuru/server/python_modules/lib/python3.10/site-packages/alembic/command.py", line 320, in upgrade
    script.run_env()
  File "/home/zim/szuru/server/python_modules/lib/python3.10/site-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/zim/szuru/server/python_modules/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/zim/szuru/server/python_modules/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/zim/szuru/server/szurubooru/migrations/env.py", line 22, in <module>
    import szurubooru.config  # noqa: E402
  File "/home/zim/szuru/server/szurubooru/migrations/../../szurubooru/config.py", line 65, in <module>
    config = _read_config()
  File "/home/zim/szuru/server/szurubooru/migrations/../../szurubooru/config.py", line 53, in _read_config
    ret = _file_config("config.yaml.dist")
  File "/home/zim/szuru/server/szurubooru/migrations/../../szurubooru/config.py", line 48, in _file_config
    with open(filename) as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml.dist'
```
same issue on arch and ubuntu
idk if its an issue with the database being wrongly set in the config but heres what the end of `config.yaml` looks like:
```
## ONLY SET THESE IF DEPLOYING OUTSIDE OF DOCKER
debug: 0 # generate server logs?
show_sql: 0 # show sql in server logs?
data_url: /data/
data_dir: /var/www/data
## usage: schema://user:password@host:port/database_name
## example: postgres://szuru:dog@localhost:5432/szuru_test
database:
        postgres://szuru:<mypassword>@localhost:5432/szuru
```

**Comment by ziimro** [comment]
fixed by moving 'config.yaml.dist' into the server directory
