### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by DrJake1** [rr-/szurubooru#548]
Hello,

I've been trying to get this working for several days now and I'm coming up on the constant problem of being unable to upload anything at all. 

I get this error:
`2023-01-28 03:19:58 szuru-server-1  | Traceback (most recent call last):
2023-01-28 03:19:58 szuru-server-1  |   File "/usr/lib/python3.8/site-packages/waitress/channel.py", line 350, in service
2023-01-28 03:19:58 szuru-server-1  |     task.service()
2023-01-28 03:19:58 szuru-server-1  |   File "/usr/lib/python3.8/site-packages/waitress/task.py", line 171, in service
2023-01-28 03:19:58 szuru-server-1  |     self.execute()
2023-01-28 03:19:58 szuru-server-1  |   File "/usr/lib/python3.8/site-packages/waitress/task.py", line 441, in execute
2023-01-28 03:19:58 szuru-server-1  |     app_iter = self.channel.server.application(environ, start_response)
2023-01-28 03:19:58 szuru-server-1  |   File "/opt/app/szurubooru/rest/app.py", line 104, in application
2023-01-28 03:19:58 szuru-server-1  |     response = handler(ctx, match.groupdict())
2023-01-28 03:19:58 szuru-server-1  |   File "/opt/app/szurubooru/api/upload_api.py", line 19, in create_temporary_file
2023-01-28 03:19:58 szuru-server-1  |     token = file_uploads.save(content)
2023-01-28 03:19:58 szuru-server-1  |   File "/opt/app/szurubooru/func/file_uploads.py", line 29, in save
2023-01-28 03:19:58 szuru-server-1  |     files.save(path, content)
2023-01-28 03:19:58 szuru-server-1  |   File "/opt/app/szurubooru/func/files.py", line 41, in save
2023-01-28 03:19:58 szuru-server-1  |     os.makedirs(os.path.dirname(full_path), exist_ok=True)
2023-01-28 03:19:58 szuru-server-1  |   File "/usr/lib/python3.8/os.py", line 223, in makedirs
2023-01-28 03:19:58 szuru-server-1  |     mkdir(name, mode)
2023-01-28 03:19:58 szuru-server-1  | PermissionError: [Errno 13] Permission denied: '/data/temporary-uploads'`
which, according to a few other people as well as the wiki, is fixed by using `chown -R 1000:1000 /var/local/szurubooru/data` but that just says 'no such file or directory'. I tried creating that directory and was then able to use chown but I still get the error.

**Comment by neobooru** [comment]
Did you change the `MOUNT_DATA` inside the `.env` file? Whatever directory that points to needs to be writable by szurubooru.

**Comment by DrJake1** [comment]
> Did you change the `MOUNT_DATA` inside the `.env` file? Whatever directory that points to needs to be writable by szurubooru.

Yes, I pointed the directory to inside the `szuru` root folder (so the full path would be `C:\Users\(user)\Documents\szuru\var\local\szurubooru\data`, which is reflected in `.env` as well)

**Comment by neobooru** [comment]
Hm I don't think I fully understand. Could you try setting MOUNT_DATA and MOUNT_SQL like this? (I assume you are using windows)

```
MOUNT_DATA=C:\Szurubooru\data
MOUNT_SQL=C:\Szurubooru\sql
```

**Comment by TiredSysOp** [comment]
You tried running with admin rights to see if that clears everything up? Once you've done that you can start with the arduous task of setting permissions in windows properly.
