### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by nonoes125** [rr-/szurubooru#563]
I followed the installation tutorial: https://github.com/rr-/szurubooru/blob/master/doc/INSTALL.md

But when I tried to register an account it gives me the: Internal Server Error message
![srv00](https://user-images.githubusercontent.com/129543077/229192325-aad65100-c101-4ea7-bc01-5e3cab69811b.png), No idea what to do from now on.

 docker-compose logs -f
`szuru-sql-1     | 2023-03-31 17:48:51.804 UTC [1] LOG:  background worker "logical replication launcher" (PID 28) exited with exit code 1
szuru-sql-1     | 2023-03-31 17:48:51.824 UTC [23] LOG:  shutting down
szuru-sql-1     | 2023-03-31 17:48:51.824 UTC [23] PANIC:  could not open control file "global/pg_control": Permission denied
szuru-sql-1     | 2023-03-31 17:48:51.824 UTC [1] LOG:  checkpointer process (PID 23) was terminated by signal 6: Aborted
szuru-sql-1     | 2023-03-31 17:48:51.824 UTC [1] LOG:  terminating any other active server processes
szuru-sql-1     | 2023-03-31 17:48:51.824 UTC [27] LOG:  could not open temporary statistics file "pg_stat/global.tmp": Permission denied
szuru-sql-1     | 2023-03-31 17:48:51.827 UTC [1] LOG:  abnormal database system shutdown
szuru-sql-1     | 2023-03-31 17:48:51.872 UTC [1] LOG:  database system is shut down
szuru-sql-1     | 
szuru-sql-1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
szuru-sql-1     | 
szuru-sql-1     | 2023-03-31 17:49:37.113 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
szuru-sql-1     | 2023-03-31 17:49:37.113 UTC [1] LOG:  listening on IPv6 address "::", port 5432
szuru-sql-1     | 2023-03-31 17:49:37.120 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
szuru-sql-1     | 2023-03-31 17:49:37.143 UTC [23] LOG:  database system was interrupted; last known up at 2023-03-31 17:17:05 UTC
szuru-sql-1     | 2023-03-31 17:49:38.375 UTC [23] LOG:  database system was not properly shut down; automatic recovery in progress
szuru-sql-1     | 2023-03-31 17:49:38.379 UTC [23] LOG:  redo starts at 0/175E500
szuru-sql-1     | 2023-03-31 17:49:38.379 UTC [23] LOG:  invalid record length at 0/175E538: wanted 24, got 0
szuru-sql-1     | 2023-03-31 17:49:38.379 UTC [23] LOG:  redo done at 0/175E500
szuru-sql-1     | 2023-03-31 17:49:38.423 UTC [1] LOG:  database system is ready to accept connections
szuru-sql-1     | 2023-03-31 17:50:10.557 UTC [1] LOG:  received fast shutdown request
szuru-sql-1     | 2023-03-31 17:50:10.559 UTC [1] LOG:  aborting any active transactions
szuru-sql-1     | 2023-03-31 17:50:10.562 UTC [1] LOG:  background worker "logical replication launcher" (PID 29) exited with exit code 1
szuru-sql-1     | 2023-03-31 17:50:10.567 UTC [24] LOG:  shutting down
szuru-sql-1     | 2023-03-31 17:50:10.590 UTC [1] LOG:  database system is shut down
szuru-sql-1     | 
szuru-sql-1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
szuru-sql-1     | 
szuru-sql-1     | 2023-03-31 17:51:33.853 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
szuru-sql-1     | 2023-03-31 17:51:33.853 UTC [1] LOG:  listening on IPv6 address "::", port 5432
szuru-sql-1     | 2023-03-31 17:51:33.859 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
szuru-sql-1     | 2023-03-31 17:51:33.888 UTC [22] LOG:  database system was shut down at 2023-03-31 17:50:10 UTC
szuru-sql-1     | 2023-03-31 17:51:33.936 UTC [1] LOG:  database system is ready to accept connections
szuru-client-1  | 172.18.0.1 -> GET / HTTP/1.1 [200] - referer: - -
szuru-client-1  | 172.18.0.1 -> GET /css/app.min.css HTTP/1.1 [200] - referer: http://127.0.0.1/ -
szuru-client-1  | 172.18.0.1 -> GET /css/vendor.min.css HTTP/1.1 [200] - referer: http://127.0.0.1/ -
szuru-client-1  | 172.18.0.1 -> GET /api/info HTTP/1.1 [200] - referer: http://127.0.0.1/ -
szuru-server-1  | [2023-03-31 17:54:59] szurubooru.middleware.request_logger GET /info (user=None, queries=2)
szuru-server-1  | [2023-03-31 17:54:59] szurubooru.middleware.request_logger GET /info (user=None, queries=2)
szuru-client-1  | 172.18.0.1 -> GET /api/info HTTP/1.1 [200] - referer: http://127.0.0.1/ -
szuru-client-1  | 172.18.0.1 -> GET /fonts/open_sans.woff2 HTTP/1.1 [200] - referer: http://127.0.0.1/css/app.min.css -
szuru-client-1  | 172.18.0.1 -> GET /img/apple-touch-icon.png HTTP/1.1 [200] - referer: http://127.0.0.1/ -
szuru-client-1  | 172.18.0.1 -> GET /img/favicon.png HTTP/1.1 [200] - referer: http://127.0.0.1/ -
szuru-client-1  | 172.18.0.1 -> GET /api/tag-categories HTTP/1.1 [200] - referer: http://127.0.0.1/ -
szuru-server-1  | [2023-03-31 17:55:00] szurubooru.middleware.request_logger GET /tag-categories (user=None, queries=1)
szuru-server-1  | [2023-03-31 17:55:00] szurubooru.middleware.request_logger GET /pool-categories (user=None, queries=1)
szuru-client-1  | 172.18.0.1 -> GET /api/pool-categories HTTP/1.1 [200] - referer: http://127.0.0.1/ -
szuru-server-1  | [2023-03-31 17:55:23] szurubooru.middleware.request_logger POST /users (user=None, queries=1)
szuru-server-1  | [2023-03-31 17:55:23] waitress Exception while serving /users
szuru-server-1  | Traceback (most recent call last):
szuru-server-1  |   File "/usr/lib/python3.8/site-packages/waitress/channel.py", line 350, in service
szuru-server-1  |     task.service()
szuru-server-1  |   File "/usr/lib/python3.8/site-packages/waitress/task.py", line 171, in service
szuru-server-1  |     self.execute()
szuru-server-1  |   File "/usr/lib/python3.8/site-packages/waitress/task.py", line 441, in execute
szuru-server-1  |     app_iter = self.channel.server.application(environ, start_response)
szuru-server-1  |   File "/opt/app/szurubooru/rest/app.py", line 104, in application
szuru-server-1  |     response = handler(ctx, match.groupdict())
szuru-server-1  |   File "/opt/app/szurubooru/api/user_api.py", line 42, in create_user
szuru-server-1  |     user = users.create_user(name, password, email)
szuru-server-1  |   File "/opt/app/szurubooru/func/users.py", line 219, in create_user
szuru-server-1  |     update_user_password(user, password)
szuru-server-1  |   File "/opt/app/szurubooru/func/users.py", line 260, in update_user_password
szuru-server-1  |     password_hash, revision = auth.get_password_hash(
szuru-server-1  |   File "/opt/app/szurubooru/func/auth.py", line 31, in get_password_hash
szuru-server-1  |     (config.config["secret"] + salt + password).encode("utf8")
szuru-server-1  | TypeError: unsupported operand type(s) for +: 'int' and 'str'
szuru-client-1  | 172.18.0.1 -> POST /api/users HTTP/1.1 [500] - referer: http://127.0.0.1/register -`

**Comment by parallax4** [comment]
Is it possible you set the `secret` value in the config to a number rather than a string?

**Comment by TiredSysOp** [comment]
Read the log again. Need to set permissions in the host filesystem for Szurubooru

**Comment by TiredSysOp** [comment]
chown -R 1000:1000 /var/local/szurubooru

Or a dirty 775 if you've lost all hope. Ensure you do this to the directory that Szurubooru is "installed".
